from __future__ import annotations

DEFAULT_OPENAI_MODEL = "gpt-5.1-codex-mini"

DEFAULT_RUN_ID_LENGTH = 12
DEFAULT_RUN_LOCK_STALE_SECONDS = 21600

DEFAULT_WINDOW_HOURS = 24
DEFAULT_SCORE_CACHE_MAX_AGE_HOURS = 24

DIGEST_MUST_READ_LIMIT = 5
DIGEST_SKIM_LIMIT = 10
DIGEST_VIDEO_LIMIT = 5
DIGEST_TOTAL_LIMIT = 20

GITHUB_DEFAULT_PER_PAGE = 5

WEB_DEFAULT_HOST = "127.0.0.1"
WEB_DEFAULT_PORT = 8787
WEB_PROGRESS_HISTORY_LIMIT = 40
